SECRET_KEY = "dev"  # Use a secure value in production
MONGO_URI = "mongodb://127.0.0.1:27017/users"
MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = "username"
MAIL_PASSWORD = "password"
MAIL_DEFAULT_SENDER = ("sender", "username")
SERVER_NAME = "127.0.0.1:5000"  # Needed to generate the HTML email
WRITER_WEBHOOK = None  # Webhook where we will get notified on a new application
