services:
  web:
    build: .
    container_name: goodmorningtech_web
    restart: unless-stopped
    environment:
      - FLASK_APP=index.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: goodmorningtech_nginx
    restart: unless-stopped
    ports:
      - 5000:80
    depends_on:
      - web
